unit Milon;

interface

uses AlephBet;

const
  ADAR=ALEPH+DALET+RAISH;
  ADARALEPH=ADAR+SPACE+ALEPH;
  ADARBAIS=ADAR+SPACE+BAIS;
  CHESVAN=CHES+SHIN+VOV+ENDNUN;
  ELUL=ALEPH+LAMED+VOV+LAMED;
  IYAR=ALEPH+YUD+YUD+RAISH;
  KISLEV=CHOF+SAMECH+LAMED+VOV;
  NISSAN=NUN+YUD+SAMECH+ENDNUN;
  OV=ALEPH+BAIS;
  TAMMUZ=TOF+MEM+VOV+ZAYIN;
  TEVES=TESS+BAIS+TOF;
  SHEVOT=SHIN+BAIS+TESS;
  SIVAN=SAMECH+YUD+VOV+ENDNUN;
  TISHREI=TOF+SHIN+RAISH+YUD;

  H_MOLAD=MEM+VOV+LAMED+DALET;
  H_ROSH=RAISH+ALEPH+SHIN;
  H_SHONNOH=SHIN+NUN+HEY;
  H_ROSH_HASHONNOH=H_ROSH+SPACE+HEY+H_SHONNOH;

  H_TEKUFAH=TOF+KUF+VOV+PAY+HEY;


implementation

end.
